language: common-lisp
sudo: required

env:
  matrix:
    - LISP=clisp

install:
  # Install cl-travis
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - cl -e '(ql:quickload :lista)
           (unless (lista:test-lista-5)
             (uiop:quit 1))'
